name: TenJava Judge
author: TenJava
version: '1.1'
main: 'com.tenjava.downloader.Downloader'
commands:
  download:
    usage: '/<command> <entry> - Eg: /<command> turt2live-t3'
    description: Downloads a participant entry
    permission: 'tenjava.download'
    aliases: ['dl', 'tjdownload', 'judge']
permissions:
  'tenjava.download':
    description: Allows people to download plugins
    default: op